In [5]:
import pandas as pd

print("DATA GAMES")
df_games = pd.read_csv("../data/raw/games.csv")
display(df_games.head())
print("\nInfo Data Games: ")
df_games.info()

DATA GAMES

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

Info Data Games:
<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          50872 non-null  int64
 1   title           50872 non-null  str
 2   date_release    50872 non-null  str
 3   win             50872 non-null  bool
 4   mac             50872 non-null  bool
 5   linux           50872 non-null  bool
 6   rating          50872 non-null  str
 7   positive_ratio  50872 non-null  int64
 8   user_reviews    50872 non-null  int64
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool
dtypes: bool(4), float64(3), int64(3), str(3)
memory usage: 3.7 MB

In [7]:
print("DATA REKOMENDASI")
df_recom = pd.read_csv("../data/raw/recommendations.csv", nrows=10000)
display(df_recom.head())
print("\nInfo Data Rekomendasi: ")
df_recom.info()

DATA REKOMENDASI

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,975370,0,0,2022-12-12,True,36.3,51580,0
1,304390,4,0,2017-02-17,False,11.5,2586,1
2,1085660,2,0,2019-11-17,True,336.5,253880,2
3,703080,0,0,2022-09-23,True,27.4,259432,3
4,526870,0,0,2021-01-10,True,7.9,23869,4

Info Data Rekomendasi:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          10000 non-null  int64
 1   helpful         10000 non-null  int64
 2   funny           10000 non-null  int64
 3   date            10000 non-null  str
 4   is_recommended  10000 non-null  bool
 5   hours           10000 non-null  float64
 6   user_id         10000 non-null  int64
 7   review_id       10000 non-null  int64
dtypes: bool(1), float64(1), int64(5), str(1)
memory usage: 556.8 KB

In [8]:
print("DATA METADATA")
df_meta = pd.read_json('../data/raw/games_metadata.json', lines=True)

display(df_meta.head())
print("\nInfo Data Metadata:")
df_meta.info()

DATA METADATA

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,,[Action]
2,113020,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

Info Data Metadata:
<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   app_id       50872 non-null  int64
 1   description  50872 non-null  str
 2   tags         50872 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 1.2+ MB